# Generated by Django 4.1.4 on 2023-01-24 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('authId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('authName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('bookName', models.CharField(max_length=50)),
                ('genres', models.CharField(default='NIL', max_length=50)),
                ('copies', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Book2Auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.book')),
            ],
        ),
    ]
