# Generated by Django 4.1.4 on 2023-01-22 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bookAuth',
        ),
    ]
