# Generated by Django 4.1.4 on 2023-01-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_remove_book_bookauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.CharField(default='NIL', max_length=50),
        ),
    ]
