# Generated by Django 4.1.5 on 2023-01-17 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='authors',
            new_name='author',
        ),
        migrations.RenameModel(
            old_name='books',
            new_name='book',
        ),
    ]
