# Generated by Django 4.1.4 on 2023-01-22 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book2auth',
            name='auth',
        ),
        migrations.RemoveField(
            model_name='book2auth',
            name='book',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Book2Auth',
        ),
    ]
